version: '3'
services:
    server:
        container_name: responsive-webapp-server
        image: responsive-webapp/server
        build:
            context: ./server
        ports:
            - "3000:3000"
    client:
        container_name: responsive-webapp-client
        image: responsive-webapp/client
        build:
            context: ./client
        ports:
            - "80:80"
            - "443:443"
        command: [nginx, '-g', 'daemon off;']
